spring:
  application:
    name: comment
  datasource:
    url: jdbc:h2:tcp://localhost/~/comment
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true